version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: ~/repo

    steps:
      - run: echo build step

  test:
    docker:
      - image: circleci/golang:1.9

    working_directory: ~/repo

    steps:
      - run: echo test step

  deploy:
    docker:
      - image: circleci/golang:1.9

    working_directory: ~/repo

    steps:
      - run: echo deploy step


workflows:
  version: 2
  build-and-test:
    jobs:
      -build
      - test:
          requires:
            -build
      - deploy:
          requires:
            -test